// GENERATED by scripts/generate-themes.mjs — do not edit by hand.
// Regenerate: node scripts/generate-themes.mjs
export const THEME_IDS = [
  'blue',
  'purple',
  'green',
  'teal',
  'amber',
  'magenta',
  'fuchsia',
  'rose',
  'lime',
  'coral',
] as const;
export type HtmdxThemeId = (typeof THEME_IDS)[number];

export const THEME_CSS = `
  [data-htmdx-theme="purple"] {
    --htmdx-accent: #6F43CA;
    --htmdx-accent-soft: #F3EFFB;
    --htmdx-accent-edge: #E9E1F7;
    --primary: #6F43CA;
    --ring: #6F43CA;
    --accent: #F3EFFB;
    --accent-foreground: #460095;
  }
  [data-htmdx-theme="green"] {
    --htmdx-accent: #008321;
    --htmdx-accent-soft: #E9F5EE;
    --htmdx-accent-edge: #D4ECDF;
    --primary: #008321;
    --ring: #008321;
    --accent: #E9F5EE;
    --accent-foreground: #004D00;
  }
  [data-htmdx-theme="teal"] {
    --htmdx-accent: #008577;
    --htmdx-accent-soft: #E6F5F5;
    --htmdx-accent-edge: #CEECEC;
    --primary: #008577;
    --ring: #008577;
    --accent: #E6F5F5;
    --accent-foreground: #004A3F;
  }
  [data-htmdx-theme="amber"] {
    --htmdx-accent: #AB4100;
    --htmdx-accent-soft: #F8F0E6;
    --htmdx-accent-edge: #F2E3CE;
    --primary: #AB4100;
    --ring: #AB4100;
    --accent: #F8F0E6;
    --accent-foreground: #740200;
  }
  [data-htmdx-theme="magenta"] {
    --htmdx-accent: #9A2DA3;
    --htmdx-accent-soft: #F9EEF6;
    --htmdx-accent-edge: #F3DEEE;
    --primary: #9A2DA3;
    --ring: #9A2DA3;
    --accent: #F9EEF6;
    --accent-foreground: #670071;
  }
  [data-htmdx-theme="fuchsia"] {
    --htmdx-accent: #AF1C7B;
    --htmdx-accent-soft: #FBEDF2;
    --htmdx-accent-edge: #F8DDE6;
    --primary: #AF1C7B;
    --ring: #AF1C7B;
    --accent: #FBEDF2;
    --accent-foreground: #78004D;
  }
  [data-htmdx-theme="rose"] {
    --htmdx-accent: #BB0E48;
    --htmdx-accent-soft: #FDEDED;
    --htmdx-accent-edge: #FADDDC;
    --primary: #BB0E48;
    --ring: #BB0E48;
    --accent: #FDEDED;
    --accent-foreground: #83001E;
  }
  [data-htmdx-theme="lime"] {
    --htmdx-accent: #5C7200;
    --htmdx-accent-soft: #EFF4E8;
    --htmdx-accent-edge: #DFEAD3;
    --primary: #5C7200;
    --ring: #5C7200;
    --accent: #EFF4E8;
    --accent-foreground: #304300;
  }
  [data-htmdx-theme="coral"] {
    --htmdx-accent: #B92900;
    --htmdx-accent-soft: #FBEFE8;
    --htmdx-accent-edge: #F7E0D2;
    --primary: #B92900;
    --ring: #B92900;
    --accent: #FBEFE8;
    --accent-foreground: #800000;
  }
`;
