// Offline generator: rotates the default purple M3 palette to each theme's
// hue in OKLCh while preserving each token's lightness and chroma. Output is
// committed to src/themes.ts; this script is not part of the build/test path.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { contrastRatio, hexToOklch, oklchToHex } from './oklch.mjs';

const indexPath = fileURLToPath(new URL('../src/index.ts', import.meta.url));
const outPath = process.argv[2] ?? fileURLToPath(new URL('../src/themes.ts', import.meta.url));

const SEEDS = {
  blue: '#2F55D4',
  green: '#1F8A4C',
  teal: '#0E8C82',
  amber: '#C77A00',
  magenta: '#A937B3',
  fuchsia: '#BA3186',
  rose: '#C23255',
  lime: '#617100',
  coral: '#B24A00',
};

// Semantic error colors and shadows stay stable across decorative themes.
const KEEP = new Set([
  'md-sys-color-error',
  'md-sys-color-on-error',
  'md-sys-color-error-container',
  'md-sys-color-on-error-container',
  'md-sys-color-shadow',
]);

function parseBaseTokens(src) {
  const rootStart = src.indexOf(':root {');
  const block = src.slice(rootStart, src.indexOf('}', rootStart));
  return Array.from(
    block.matchAll(/--(md-sys-color-[a-z0-9-]+):\s*(#[0-9A-Fa-f]{6})\s*;/g),
    ([, name, hex]) => ({ name, hex }),
  );
}

function rotate(hex, delta) {
  const { l, c, h } = hexToOklch(hex);
  if (c < 0.001) {
    return hex.toUpperCase();
  }
  return oklchToHex({ l, c, h: (h + delta + 360) % 360 });
}

function snapToAA(hex, background) {
  let current = hex;
  let { l, c, h } = hexToOklch(hex);
  while (contrastRatio(current, background) < 4.5 && l > 0) {
    l -= 0.005;
    current = oklchToHex({ l, c, h });
  }
  return current;
}

const base = parseBaseTokens(readFileSync(indexPath, 'utf8'));
const primary = base.find((token) => token.name === 'md-sys-color-primary');
if (!primary) {
  throw new Error('--md-sys-color-primary not found in src/index.ts :root block');
}
const baseHue = hexToOklch(primary.hex).h;

const blocks = Object.entries(SEEDS).map(([id, seed]) => {
  const delta = hexToOklch(seed).h - baseHue;
  const lines = base.map(({ name, hex }) => {
    let value = KEEP.has(name) ? hex : rotate(hex, delta);
    if (name === 'md-sys-color-primary') {
      value = snapToAA(value, '#FFFFFF');
    }
    return `    --${name}: ${value};`;
  });
  return `  [data-htmdx-theme="${id}"] {\n${lines.join('\n')}\n  }`;
});

const ids = ['purple', ...Object.keys(SEEDS)];
const idsLiteral = `[\n${ids.map((id) => `  '${id}',`).join('\n')}\n]`;

const out = `// GENERATED by scripts/generate-themes.mjs — do not edit by hand.
// Regenerate: node scripts/generate-themes.mjs
export const THEME_IDS = ${idsLiteral} as const;
export type HtmdxThemeId = (typeof THEME_IDS)[number];

export const THEME_CSS = \`
${blocks.join('\n')}
\`;
`;

writeFileSync(outPath, out);
// oxlint-disable-next-line no-console -- progress output for a manually-run CLI generator
console.log(`Wrote ${outPath} (${base.length} tokens x ${blocks.length} themes)`);
