// Offline generator: rotates the default blue palette to each theme's hue in
// OKLCh, keeping lightness + chroma so every theme shares the same DNA, then
// snaps text/interactive tokens to WCAG AA. Output is committed to
// src/themes.ts; this script is not part of the build/test path.
//
// Regenerate: node scripts/generate-themes.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { contrastRatio, hexToOklch, oklchToHex } from './oklch.mjs';

const indexPath = fileURLToPath(new URL('../src/index.ts', import.meta.url));
const outPath = process.argv[2] ?? fileURLToPath(new URL('../src/themes.ts', import.meta.url));

// Themes are defined by a hue only; each seed hex's OKLCh hue is all that is
// used (lightness + chroma always come from the blue token being rotated).
const SEEDS = {
  purple: '#7C3AED',
  green: '#1F8A4C',
  teal: '#0E8C82',
  amber: '#C77A00',
  magenta: '#A937B3',
  fuchsia: '#BA3186',
  rose: '#C23255',
  lime: '#617100',
  coral: '#B24A00',
};

const BASE_TOKENS = ['htmdx-accent', 'htmdx-accent-soft', 'htmdx-accent-edge'];
const ACCENT_FOREGROUND_LIGHTNESS = 0.35;

function parseBaseTokens(src) {
  const rootStart = src.indexOf(':root {');
  const block = src.slice(rootStart, src.indexOf('}', rootStart));
  return new Map(
    BASE_TOKENS.map((name) => {
      const match = block.match(new RegExp(`--${name}:\\s*(#[0-9A-Fa-f]{6})\\s*;`));
      if (!match) throw new Error(`--${name} not found in src/index.ts :root block`);
      return [name, match[1]];
    }),
  );
}

function rotate(hex, delta) {
  const { l, c, h } = hexToOklch(hex);
  return oklchToHex({ l, c, h: (h + delta + 360) % 360 });
}

function withLightness(hex, l) {
  return oklchToHex({ ...hexToOklch(hex), l });
}

function snapToAA(hex, background) {
  let current = hex;
  let { l, c, h } = hexToOklch(hex);
  while (contrastRatio(current, background) < 4.5 && l > 0) {
    l -= 0.005;
    current = oklchToHex({ l, c, h });
  }
  return current;
}

const base = parseBaseTokens(readFileSync(indexPath, 'utf8'));
const baseHue = hexToOklch(base.get('htmdx-accent')).h;

const blocks = Object.entries(SEEDS).map(([id, seed]) => {
  const delta = hexToOklch(seed).h - baseHue;
  const accent = snapToAA(rotate(base.get('htmdx-accent'), delta), '#FFFFFF');
  const soft = rotate(base.get('htmdx-accent-soft'), delta);
  const edge = rotate(base.get('htmdx-accent-edge'), delta);
  const accentForeground = snapToAA(withLightness(accent, ACCENT_FOREGROUND_LIGHTNESS), soft);
  const lines = [
    `    --htmdx-accent: ${accent};`,
    `    --htmdx-accent-soft: ${soft};`,
    `    --htmdx-accent-edge: ${edge};`,
    `    --primary: ${accent};`,
    `    --ring: ${accent};`,
    `    --accent: ${soft};`,
    `    --accent-foreground: ${accentForeground};`,
  ];
  return `  [data-htmdx-theme="${id}"] {\n${lines.join('\n')}\n  }`;
});

const ids = ['blue', ...Object.keys(SEEDS)];
const idsLiteral = `[\n${ids.map((id) => `  '${id}',`).join('\n')}\n]`;

const out = `// GENERATED by scripts/generate-themes.mjs — do not edit by hand.
// Regenerate: node scripts/generate-themes.mjs
export const THEME_IDS = ${idsLiteral} as const;
export type HtmdxThemeId = (typeof THEME_IDS)[number];

export const THEME_CSS = \`
${blocks.join('\n')}
\`;
`;

writeFileSync(outPath, out);
// oxlint-disable-next-line no-console -- progress output for a manually-run CLI generator
console.log(`Wrote ${outPath} (${blocks.length} theme blocks)`);
