// Offline generator: rotates the purple palette to each theme's hue in HCT,
// keeping tone + chroma so every theme shares the same DNA. Output is committed
// to src/themes.ts. Re-run with: node scripts/generate-themes.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { Hct, argbFromHex, hexFromArgb } from '@material/material-color-utilities';

const indexPath = fileURLToPath(new URL('../src/index.ts', import.meta.url));
const outPath = fileURLToPath(new URL('../src/themes.ts', import.meta.url));

// Themes are defined by a hue only; the seed hex's HCT hue is all that is used
// (tone + chroma always come from the purple token being rotated). Tune these
// hexes during review to hit the target look and the contrast bar.
const SEEDS = {
  blue: '#2F55D4',
  green: '#1F8A4C',
  teal: '#0E8C82',
  amber: '#C77A00',
  magenta: '#A937B3',
  fuchsia: '#BA3186',
  rose: '#C23255',
  lime: '#617100',
  coral: '#B24A00',
};

// Tokens kept identical across themes (semantic red must stay red).
const KEEP = new Set([
  'md-sys-color-error',
  'md-sys-color-on-error',
  'md-sys-color-error-container',
  'md-sys-color-on-error-container',
  'md-sys-color-shadow',
]);

function parsePurpleTokens(src) {
  const rootStart = src.indexOf(':root {');
  const rootEnd = src.indexOf('}', rootStart);
  const block = src.slice(rootStart, rootEnd);
  const tokens = [];
  const re = /--(md-sys-color-[a-z0-9-]+):\s*(#[0-9A-Fa-f]{6})\s*;/g;
  let m;
  while ((m = re.exec(block))) {
    tokens.push({ name: m[1], hex: m[2] });
  }
  return tokens;
}

function rotate(hex, delta) {
  const hct = Hct.fromInt(argbFromHex(hex));
  const rotated = Hct.from((hct.hue + delta + 360) % 360, hct.chroma, hct.tone);
  return hexFromArgb(rotated.toInt()).toUpperCase();
}

const src = readFileSync(indexPath, 'utf8');
const purple = parsePurpleTokens(src);
const purplePrimary = purple.find((t) => t.name === 'md-sys-color-primary');
const purpleHue = Hct.fromInt(argbFromHex(purplePrimary.hex)).hue;

const blocks = Object.entries(SEEDS).map(([id, seed]) => {
  const delta = Hct.fromInt(argbFromHex(seed)).hue - purpleHue;
  const lines = purple.map((t) => {
    const value = KEEP.has(t.name) ? t.hex : rotate(t.hex, delta);
    return `    --${t.name}: ${value};`;
  });
  return `  [data-htmdx-theme="${id}"] {\n${lines.join('\n')}\n  }`;
});

const ids = ['purple', ...Object.keys(SEEDS)];
const idsLiteral = `[${ids.map((id) => `'${id}'`).join(', ')}]`;

const out = `// GENERATED by scripts/generate-themes.mjs — do not edit by hand.
// Regenerate: node scripts/generate-themes.mjs
export const THEME_IDS = ${idsLiteral} as const;
export type HtmdxThemeId = (typeof THEME_IDS)[number];

export const THEME_CSS = \`
${blocks.join('\n')}
\`;
`;

writeFileSync(outPath, out);
// eslint-disable-next-line no-console -- progress output for a manually-run CLI generator
console.log(`Wrote ${outPath} (${purple.length} tokens x ${blocks.length} themes)`);
