export {
  createDefinitionRegistry,
  validateConstraints,
  validateDefinition,
  type HtmdxBodyFormat,
  type HtmdxBooleanProp,
  type HtmdxComponent,
  type HtmdxComponentDefinitions,
  type HtmdxJsonProp,
  type HtmdxJsonValue,
  type HtmdxNumberProp,
  type HtmdxProp,
  type HtmdxPropType,
  type HtmdxStringProp,
} from '../component-definition';
